### ISSUE TITLE
Gnome 45 / new versions

### ISSUE THREAD

**Issue by Totto16** [gjsify/types#1]
There are some new versions of many libraries, any plans to build those?

These type definitions are very useful ❤️ 

And keep up the good work, even if not so many use those, these extension developers are all using js 😭 😂

**Comment by JumpLink** [comment]
@Totto16 I have now updated the types, are you still missing something?

**Comment by Totto16** [comment]
@JumpLink Thank you very much ❤️ 

But do you have, by any chance also types for


Shell 13
Clutter 13
St 13 
Cogl 13 
Meta 13 

And there might be also other newer version for other packages 😓

**Comment by JumpLink** [comment]
@Totto16 I can release the types for this versions as soon as Fedora 39 is released (and I have upgrade my Fedora 38) or as soon as this Gir files are added to https://github.com/nemequ/vala-girs/tree/master/gir-1.0

**Comment by JumpLink** [comment]
@Totto16 Should be published now, e.g. see https://www.npmjs.com/package/@girs/shell-13

Feel free to reopen this issue if something is still missing.

**Comment by bennypowers** [comment]
docs for `@girs/glib` say you need to import with a query param

```
import GLib from 'gi://GLib?version=2.0';
```

This will actually break shell extensions at runtime though. Could you update the types so that extension developers can use them by copying the examples on https://gjs.guide/extensions/upgrading/gnome-shell-45.html#esm?

**Comment by JumpLink** [comment]
Hey @bennypowers,

The challenge we're facing is related to the different versions of the libraries we're using. If I define the types without specifying a version, it leads to conflicts among the generated types for various versions. This approach has its roots in ts-for-gir where types are often generated locally for specific projects rather than as NPM packages.

Typically, when generating types for a single version, we don't include the version string (More precisely, it is generated once with versionsstring and once without, so that both are possible, [as you can see in this template](https://github.com/gjsify/ts-for-gir/blob/3.x/packages/generator-typescript/templates/gjs/module-ambient.d.ts)). However, it becomes necessary when generating types for multiple versions simultaneously, which is what happens when I create all the NPM packages.

That said, there's room for improvement here. If we're generating types as NPM packages, we might be able to skip the version string. I think this warrants a discussion and possibly an issue in ts-for-gir, especially considering that not all packages need to be installed at the same time.

Let's explore this further and see how we can streamline the process.
