### ISSUE TITLE
Missing url on ImportMeta

### ISSUE THREAD

**Issue by swsnr** [gjsify/types#4]
In GJS, `import.meta.url` provides the URL of the current module, but it's missing in `@girs/gjs`.  I can provide a pull request, but I don't know where: As far as I understand the `gjs` types in this repository are generated, so I guess I shouldn't change them 🤔 

So where do I make a pull request? 😇

**Comment by JumpLink** [comment]
[ts-for-gir](https://github.com/gjsify/ts-for-gir) generates these types, so the PR must be made there.

If there are no conflicts with the types from other standards, you can add the types here: https://github.com/gjsify/ts-for-gir/blob/3.x/packages%2Fgenerator-typescript%2Ftemplates%2Fgjs%2Fgjs.d.ts

Otherwise here: https://github.com/gjsify/ts-for-gir/blob/3.x/packages%2Fgenerator-typescript%2Ftemplates%2Fgjs%2Fdom.d.ts

**Comment by swsnr** [comment]
@JumpLink Thanks for the pointer; I'll make an MR.

**Comment by swsnr** [comment]
@JumpLink See https://github.com/gjsify/ts-for-gir/pull/142
