### ISSUE TITLE
Gnome 46 versions

### ISSUE THREAD

**Issue by Totto16** [gjsify/types#8]
Gnome 46 again updates the core dependencies (see [here](https://gitlab.gnome.org/GNOME/gnome-shell/-/blob/main/meson.build?ref_type=heads#L13))

so there are new types for those, also gnome 46 types (`@girs/gnome-shell`) need to be added

If i can help by something, I'll be glad to help, fedora 40 release date is planned on 2024-04-16, ubuntu 24.04 2024-04-25, so if this needs to be quicker (and some extension, that update to gnome 46 earlier and use those types "need" it quicker) we / I should get those types from another source, like a VM with prereleases of those distros or gnome OS Nightly,  if I should extract types from there, just ask 👍🏼

**Comment by JumpLink** [comment]
I have now installed Fedora Rawhide (41) in GNOME Boxes, copied the gir files there into the ts-for-gir repository, generated the types and published them on NPM.

Feel free to submit new gir versions as PR as well, gir files from other projects are also welcome, then they will be generated whenever I generate and publish new NPM packages.

**Comment by JumpLink** [comment]
I have now also updated the types on `@girs/gnome-shell`, see https://github.com/gjsify/gnome-shell/issues/21.

Feel free to test it and create a new issue on `ts-for-gir` or `gnome-shell` if needed. I will close the issue tracker here, because it only contains the generated types and the issues rather belong to ts-for-gir
